spring:
  datasource:
    url: jdbc:postgresql://kartoteka-db:5432/kartoteka
    driverClassName: org.postgresql.Driver
    username: postgres
    password:

application:
  cors:
    api: "http://localhost"
    api-port: "http://localhost:4200"
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days