spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

server:
  port: 8080

logging:
  level:
    org:
      springframework: INFO